version: '3.7'

services:     
  mariadb:
    container_name: web-mariadb
    hostname: mariadb
    image: mariadb:10.5
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: webdb
      MARIADB_USER: webdb
      MARIADB_PASSWORD: password
    ports:
      - "5034:3306"
      
  web:
    container_name: 14_calculator
    hostname: app
    build: ./
    ports:
      - "5014:5014"
